name: Gamer-Disguise
version: ${git.commit.id.abbrev}
author: AgentRKID
main: io.github.agentrkid.gamerdisguise.GamerDisguise
depend: [ProtocolLib]
commands:
  disguise: null
  undisguise: null
  skin: null